config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2
    authby=secret

conn tunnel-modern
    left=10.0.0.10
    leftid=10.0.0.10
    right=10.0.0.20
    rightid=10.0.0.20
    # Weak Encryption: AES128, SHA1, DH Group 14
    ike=aes128-sha1-modp2048!
    esp=aes128-sha1!
    auto=add
