"use client";

export const dynamic = "force-dynamic";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { downloadFile, useToast } from "@/lib/toast";
import Stat from "@/components/motion/Stat";
import { AppShell } from "@/components/layout/AppShell";
import { useResolvedAnalysis } from "@/components/analysis/useResolvedAnalysis";
import {
  downloadReportPdf,
  generateExplanation,
  getExplanation,
  type Explanation,
} from "@/lib/analysis";
import { capturePackets, formatClock, formatDuration, formatCount } from "@/lib/format";

type Finding = { severity: string; category: string; description: string };

const SEV_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"] as const;

const SEV_CHIP: Record<string, string> = {
  CRITICAL: "bg-rose-500/20 text-rose-300 border-rose-500/30",
  HIGH: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  MEDIUM: "bg-sky-500/20 text-sky-300 border-sky-500/30",
  LOW: "bg-teal-500/20 text-teal-300 border-teal-500/30",
  INFO: "bg-zinc-800 text-zinc-400 border-zinc-700/50",
};

const SEV_CELL: Record<string, string> = {
  CRITICAL: "bg-rose-600 text-white border-rose-500/40",
  HIGH: "bg-amber-600 text-white border-amber-500/40",
  MEDIUM: "bg-sky-900/60 text-sky-200 border-sky-500/30",
  LOW: "bg-teal-900/60 text-teal-200 border-teal-500/30",
  INFO: "bg-zinc-800 text-zinc-300 border-zinc-700/60",
};

const IMPACT: Record<string, number> = { CRITICAL: 5, HIGH: 4, MEDIUM: 3, LOW: 2, INFO: 1 };

// Likelihood is a documented heuristic over the rule-engine category, not a CVSS score.
const LIKELIHOOD_BY_CATEGORY: Record<string, number> = {
  "Key Exchange": 5,
  Authentication: 5,
  Cryptography: 4,
  Replay: 4,
  Configuration: 3,
};

const likelihoodOf = (f: Finding) => LIKELIHOOD_BY_CATEGORY[f.category] ?? 3;
const impactOf = (f: Finding) => IMPACT[f.severity] ?? 1;

export default function FindingsPage() {
  const toast = useToast();
  const params = useSearchParams();
  const { analysis, analysisId, loading, error, empty } = useResolvedAnalysis(params.get("analysis_id"));

  const [severity, setSeverity] = useState<string>("all");
  const [query, setQuery] = useState("");
  const [selectedRow, setSelectedRow] = useState<number | null>(0);

  const [explanationState, setExplanationState] = useState<{
    forId: string;
    data: Explanation | null;
    error: string | null;
  } | null>(null);
  const [explaining, setExplaining] = useState(false);

  // Derived, not copied into state: the stored analysis is the single source of truth.
  const findings: Finding[] = useMemo(() => analysis?.findings_json ?? [], [analysis]);

  // Only trust the cached explanation if it belongs to the capture on screen.
  const explanation = explanationState?.forId === analysisId ? explanationState.data : null;
  const explainError = explanationState?.forId === analysisId ? explanationState.error : null;

  useEffect(() => {
    if (!analysisId) return;
    let dead = false;
    (async () => {
      try {
        const cached = await getExplanation(analysisId);
        if (!dead) setExplanationState({ forId: analysisId, data: cached, error: null });
      } catch (err) {
        if (!dead) {
          setExplanationState({
            forId: analysisId,
            data: null,
            error: err instanceof Error ? err.message : "AI layer unavailable.",
          });
        }
      }
    })();
    return () => {
      dead = true;
    };
  }, [analysisId]);

  const runExplanation = useCallback(
    async (regenerate: boolean) => {
      if (!analysisId) return;
      setExplaining(true);
      try {
        const result = await generateExplanation(analysisId, regenerate);
        setExplanationState({ forId: analysisId, data: result, error: null });
        toast({ title: "Explanation ready", body: `Generated by ${result.model ?? "the AI layer"}.`, kind: "ok" });
      } catch (err) {
        const message = err instanceof Error ? err.message : "AI layer unavailable.";
        setExplanationState({ forId: analysisId, data: null, error: message });
        toast({
          title: message.includes("503") ? "AI layer unavailable" : "Explanation failed",
          body: message.replace(/^\d+\s+\w+\s*—?\s*/, "").slice(0, 160),
          kind: "warn",
        });
      } finally {
        setExplaining(false);
      }
    },
    [analysisId, toast]
  );

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return findings.filter((f) => {
      const okSeverity = severity === "all" || f.severity === severity.toUpperCase();
      const okQuery = !q || f.description.toLowerCase().includes(q) || f.category.toLowerCase().includes(q);
      return okSeverity && okQuery;
    });
  }, [findings, severity, query]);

  const counts = useMemo(() => {
    const base: Record<string, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, INFO: 0 };
    for (const f of findings) base[f.severity] = (base[f.severity] ?? 0) + 1;
    return base;
  }, [findings]);

  // Clamp rather than reset in an effect, so a shrinking filter never strands the inspector.
  const safeRow = selectedRow !== null && selectedRow < filtered.length ? selectedRow : filtered.length ? 0 : null;
  const selected = safeRow !== null ? filtered[safeRow] : undefined;
  const crypto = (analysis?.config_json?.ipsec_config?.cryptography ?? {}) as Record<string, unknown>;
  const capture = analysis?.config_json?.capture;

  const exportCSV = () => {
    const esc = (v: string) => `"${v.replace(/"/g, '""')}"`;
    const rows = [["severity", "category", "description"], ...filtered.map((f) => [f.severity, f.category, esc(f.description)])];
    downloadFile(`${analysis?.filename ?? "findings"}.findings.csv`, rows.map((r) => r.join(",")).join("\n"), "text/csv");
    toast({ title: "Findings exported", body: "findings.csv downloaded.", kind: "ok" });
  };

  const exportPlan = () => {
    downloadFile(
      `${analysis?.filename ?? "remediation"}-plan.json`,
      JSON.stringify({ capture: analysis?.filename, risk: analysis?.risk_level, score: analysis?.security_score, findings }, null, 2)
    );
    toast({ title: "Remediation plan exported", body: "plan downloaded.", kind: "ok" });
  };

  const exportPdf = async () => {
    if (!analysis) return;
    try {
      await downloadReportPdf(analysis.id, analysis.filename);
      toast({ title: "PDF report downloaded", body: `${analysis.filename} report saved.`, kind: "ok" });
    } catch (err) {
      toast({ title: "PDF export failed", body: err instanceof Error ? err.message : "Try again.", kind: "warn" });
    }
  };

  if (!analysisId && !loading && (empty || error)) {
    return (
      <div className="bg-[#0c0e11] font-sans text-sm text-zinc-300 antialiased min-h-screen">
        <AppShell active="/analysis/findings" innerClassName="flex flex-col w-full text-zinc-200">
          <div className="p-8 flex flex-col gap-3">
            <p className="text-sm">
              {error ? `Findings unavailable: ${error}` : "No captures yet."}{" "}
              <Link className="underline text-teal-400" href="/analyze">
                Upload a capture
              </Link>
              .
            </p>
          </div>
        </AppShell>
      </div>
    );
  }

  return (
    <div className="bg-[#0c0e11] font-sans text-sm text-zinc-300 antialiased selection:bg-teal-500/20 selection:text-teal-200">
      <AppShell active="/analysis/findings" innerClassName="flex flex-col w-full text-zinc-200">

        {/* 1. SUB-HEADER / CONTEXT BAR */}
        <section className="bg-[#111317] border-b border-zinc-800/80 px-6 py-3.5 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex flex-col gap-1.5 min-w-0">
            <div className="flex items-center gap-2 font-mono text-xs text-zinc-500">
              <Link href="/history" className="hover:text-zinc-300 transition-colors">Captures</Link>
              <span>/</span>
              <span className="text-teal-400 font-medium">{analysis?.filename ?? "loading…"}</span>
              <span>/</span>
              <span className="text-zinc-200 font-medium">Security Findings &amp; Threat Matrix</span>
            </div>
            <div className="flex items-center flex-wrap gap-x-3 gap-y-1.5 text-xs text-zinc-400">
              <span className="flex items-center gap-2 text-zinc-100 font-medium">
                <span className="w-2 h-2 rounded-full bg-rose-500 inline-block animate-pulse"></span>
                <span className="font-display-serif font-bold text-base text-white tabular-nums"><Stat to={findings.length} /></span> Security Findings Identified
              </span>
              <span className="text-zinc-700">|</span>
              {SEV_ORDER.map((sev) => (
                <span key={sev} className={`px-2 py-0.5 rounded border font-mono font-semibold ${SEV_CHIP[sev]}`}>
                  {counts[sev]} {sev.charAt(0) + sev.slice(1).toLowerCase()}
                </span>
              ))}
              <span className="text-zinc-700">|</span>
              <span className="font-mono text-[11px] uppercase tracking-wider text-zinc-500">
                Rule engine · {analysis?.config_json?.evidence_source ?? "unknown"} evidence
              </span>
            </div>
          </div>
          <div className="flex items-center gap-2.5 flex-shrink-0">
            <button
              className="flex items-center gap-2 px-3.5 py-1.5 bg-zinc-900 border border-zinc-800 text-zinc-200 hover:bg-zinc-800/80 transition-colors rounded text-xs font-mono font-medium"
              type="button"
              onClick={exportCSV}
            >
              <span className="material-symbols-outlined text-[15px]">file_download</span>
              <span>Export CSV</span>
            </button>
            <button
              className="flex items-center gap-2 px-3.5 py-1.5 bg-teal-500/10 border border-teal-500/30 text-teal-300 hover:bg-teal-500/20 transition-colors rounded text-xs font-medium font-mono"
              type="button"
              onClick={exportPlan}
            >
              <span className="material-symbols-outlined text-[15px] text-teal-400">verified_user</span>
              <span>Remediation Plan</span>
            </button>
            <button
              className="flex items-center gap-2 px-3.5 py-1.5 bg-teal-500 text-zinc-950 hover:bg-teal-400 transition-colors rounded text-xs font-mono font-semibold disabled:opacity-50"
              type="button"
              disabled={!analysis}
              onClick={exportPdf}
            >
              <span className="material-symbols-outlined text-[15px]">picture_as_pdf</span>
              <span>Export PDF</span>
            </button>
          </div>
        </section>

        {/* 2. THREAT MATRIX + POSTURE CARDS */}
        <section className="p-6 grid grid-cols-1 xl:grid-cols-12 gap-6">
          <div className="xl:col-span-8 bg-[#111317] p-5 rounded-lg border border-zinc-800/90 flex flex-col justify-between gap-5">
            <div className="flex items-center justify-between pb-3 border-b border-zinc-800/80">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-400">
                  <span className="material-symbols-outlined text-[18px]">grid_view</span>
                </div>
                <div>
                  <h3 className="text-base font-semibold text-white tracking-tight">Impact vs. Likelihood Matrix</h3>
                  <p className="font-mono text-xs text-zinc-400">
                    Impact from rule severity · likelihood from finding category · {findings.length} plotted
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-3 font-mono text-[11px] uppercase">
                <span className="flex items-center gap-1.5 text-zinc-400"><span className="w-2 h-2 rounded-sm bg-zinc-700"></span>Info/Low</span>
                <span className="flex items-center gap-1.5 text-sky-400"><span className="w-2 h-2 rounded-sm bg-sky-500/40"></span>Medium</span>
                <span className="flex items-center gap-1.5 text-amber-400"><span className="w-2 h-2 rounded-sm bg-amber-500/40"></span>High</span>
                <span className="flex items-center gap-1.5 text-rose-400 font-semibold"><span className="w-2 h-2 rounded-full bg-rose-500"></span>Critical</span>
              </div>
            </div>

            <div className="relative grid grid-cols-5 grid-rows-5 gap-1.5 font-mono text-xs select-none h-60">
              {Array.from({ length: 25 }, (_, i) => {
                const rowIndex = Math.floor(i / 5);
                const colIndex = i % 5;
                const likelihood = 5 - rowIndex;
                const impact = colIndex + 1;
                const cellFindings = findings.filter(
                  (f) => likelihoodOf(f) === likelihood && impactOf(f) === impact
                );
                const isSelected =
                  selected !== undefined && likelihoodOf(selected) === likelihood && impactOf(selected) === impact;

                return (
                  <div
                    key={`${likelihood}-${impact}`}
                    className={`rounded p-1.5 border flex flex-col justify-between transition-colors ${
                      cellFindings.length
                        ? isSelected
                          ? "bg-zinc-800/70 border-teal-400 ring-1 ring-teal-400"
                          : "bg-zinc-900/70 border-zinc-700 hover:bg-zinc-800/60"
                        : "bg-zinc-900/50 border-zinc-800/50"
                    }`}
                  >
                    <span className="text-zinc-600 text-[10px]">
                      L{likelihood}/I{impact}
                    </span>
                    {cellFindings.map((f, idx) => (
                      <button
                        key={`${f.category}-${idx}`}
                        type="button"
                        title={`${f.severity} · ${f.category}`}
                        className={`px-1.5 py-0.5 rounded text-[10px] font-medium tracking-tight truncate border text-left ${SEV_CELL[f.severity] ?? SEV_CELL.INFO}`}
                        onClick={() => {
                          const index = filtered.indexOf(f);
                          if (index >= 0) setSelectedRow(index);
                        }}
                      >
                        {f.category}
                      </button>
                    ))}
                  </div>
                );
              })}
            </div>

            <div className="flex items-center justify-between text-zinc-500 font-mono text-[11px] uppercase pt-2.5 border-t border-zinc-800/80">
              <span className="flex items-center gap-1.5">
                <span className="material-symbols-outlined text-[13px] text-teal-400">arrow_forward</span>
                Impact: Negligible (I1) → Catastrophic (I5)
              </span>
              <span className="text-right">Likelihood: Rare (L1) → Active (L5)</span>
            </div>
          </div>

          {/* Posture cards, all derived from stored analysis columns */}
          <div className="xl:col-span-4 flex flex-col gap-3 justify-between">
            <div className="bg-[#111317] p-4 rounded-lg border border-zinc-800/90 flex items-center justify-between">
              <div className="flex flex-col gap-1">
                <span className="font-mono text-[10px] uppercase tracking-wider text-zinc-500">Forward Secrecy (PFS)</span>
                <span className={`text-base font-semibold flex items-center gap-1.5 ${crypto.pfs_enabled ? "text-teal-400" : "text-rose-400"}`}>
                  <span className="material-symbols-outlined text-[16px]">{crypto.pfs_enabled ? "lock" : "lock_open"}</span>
                  {crypto.pfs_enabled ? "Enabled" : "Disabled"}
                </span>
                <span className="text-xs text-zinc-400">
                  {crypto.pfs_enabled ? "Rekeys use an ephemeral exchange" : "Subject to retroactive decryption"}
                </span>
              </div>
              <div className={`w-14 h-14 rounded-lg flex items-center justify-center font-display-serif font-bold text-lg border ${
                crypto.pfs_enabled ? "bg-teal-500/10 border-teal-500/20 text-teal-400" : "bg-rose-500/10 border-rose-500/20 text-rose-400"
              }`}>
                {crypto.pfs_enabled ? "ON" : "OFF"}
              </div>
            </div>

            <div className="bg-[#111317] p-4 rounded-lg border border-zinc-800/90 flex items-center justify-between">
              <div className="flex flex-col gap-1">
                <span className="font-mono text-[10px] uppercase tracking-wider text-zinc-500">Key Exchange</span>
                <span className={`text-base font-semibold flex items-center gap-1.5 ${crypto.dh_group === 2 ? "text-rose-400" : "text-teal-400"}`}>
                  <span className="material-symbols-outlined text-[16px]">
                    {crypto.dh_group === 2 ? "warning" : "verified"}
                  </span>
                  {crypto.dh_group ? `DH Group ${crypto.dh_group}` : "Not observed"}
                </span>
                <span className="text-xs text-zinc-400">
                  {crypto.dh_group === 2 ? "1024-bit MODP is deprecated" : "Meets current guidance where present"}
                </span>
              </div>
              <div className={`w-14 h-14 rounded-lg flex items-center justify-center font-display-serif font-bold text-lg border ${
                crypto.dh_group === 2 ? "bg-rose-500/10 border-rose-500/20 text-rose-400" : "bg-teal-500/10 border-teal-500/20 text-teal-400"
              }`}>
                {crypto.dh_group ? String(crypto.dh_group) : "—"}
              </div>
            </div>

            <div className="bg-[#111317] p-4 rounded-lg border border-zinc-800/90 flex items-center justify-between">
              <div className="flex flex-col gap-1">
                <span className="font-mono text-[10px] uppercase tracking-wider text-zinc-500">Behavioral Anomaly</span>
                <span className={`text-base font-semibold flex items-center gap-1.5 ${analysis?.anomaly_score != null && analysis.anomaly_score < 0 ? "text-amber-400" : "text-teal-400"}`}>
                  <span className="material-symbols-outlined text-[16px]">crisis_alert</span>
                  {analysis?.anomaly_score != null ? analysis.anomaly_score.toFixed(3) : "—"}
                </span>
                <span className="text-xs text-zinc-400">
                  {analysis?.config_json?.windows_count ?? 0} ML window(s) evaluated · lower is more anomalous
                </span>
              </div>
              <div className="w-14 h-14 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center justify-center font-display-serif font-bold text-lg text-amber-400 tabular-nums">
                {analysis?.config_json?.windows_count ?? "—"}
              </div>
            </div>

            <div className="bg-[#111317] p-4 rounded-lg border border-zinc-800/90 flex items-center justify-between">
              <div className="flex flex-col gap-1">
                <span className="font-mono text-[10px] uppercase tracking-wider text-zinc-500">Capture Scope</span>
                <span className="text-base text-teal-400 font-semibold flex items-center gap-1.5">
                  <span className="material-symbols-outlined text-[16px]">dataset</span>
                  {capturePackets(analysis)} pkts
                </span>
                <span className="text-xs text-zinc-400">
                  {formatDuration(capture?.flow_duration)} span · ingested {formatClock(analysis?.created_at)}
                </span>
              </div>
              <div className="w-14 h-14 rounded-lg bg-teal-500/10 border border-teal-500/20 flex items-center justify-center font-display-serif font-bold text-sm text-teal-400">
                {SEV_ORDER.reduce((acc, s) => acc + counts[s], 0)}
              </div>
            </div>
          </div>
        </section>

        {/* 3. FILTER TOOLBAR */}
        <section className="px-6 pb-4">
          <div className="bg-[#111317] p-2 rounded-lg border border-zinc-800/90 flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center flex-wrap gap-2.5">
              <div className="flex items-center bg-zinc-900 border border-zinc-800/80 rounded-md p-0.5">
                <span className="font-mono text-[10px] uppercase text-zinc-500 px-2">Severity</span>
                <button
                  className={severity === "all" ? "px-2.5 py-1 text-xs font-mono bg-zinc-800 text-white rounded font-medium" : "px-2.5 py-1 text-xs font-mono text-zinc-400 hover:text-zinc-200 transition-colors"}
                  type="button"
                  onClick={() => { setSeverity("all"); setSelectedRow(0); }}
                >
                  All ({findings.length})
                </button>
                {SEV_ORDER.map((sev) => (
                  <button
                    key={sev}
                    className={severity === sev.toLowerCase() ? `px-2.5 py-1 text-xs font-mono rounded font-medium border ${SEV_CHIP[sev]}` : `px-2.5 py-1 text-xs font-mono transition-colors ${SEV_CHIP[sev].split(" ").find((c) => c.startsWith("text-")) ?? "text-zinc-400"}`}
                    type="button"
                    onClick={() => { setSeverity(sev.toLowerCase()); setSelectedRow(0); }}
                  >
                    {sev.charAt(0) + sev.slice(1).toLowerCase()} ({counts[sev]})
                  </button>
                ))}
              </div>

              <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-teal-500/10 border border-teal-500/20 font-mono text-[11px] text-teal-300">
                <span className="w-1.5 h-1.5 rounded-full bg-teal-400"></span>
                Deterministic rule-engine provenance
              </span>
            </div>

            <div className="flex items-center gap-2 bg-zinc-900 px-3 py-1.5 rounded border border-zinc-800 w-full sm:w-80">
              <span className="material-symbols-outlined text-[16px] text-zinc-500">search</span>
              <input
                className="bg-transparent border-0 p-0 text-xs text-zinc-200 placeholder:text-zinc-500 focus:outline-none w-full font-mono"
                placeholder="Filter by description..."
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />
              {query ? (
                <button className="font-mono text-[10px] text-zinc-500 hover:text-zinc-300 uppercase" type="button" onClick={() => setQuery("")}>
                  Clear
                </button>
              ) : null}
            </div>
          </div>
        </section>

        {/* 4. AI EXPLANATION LAYER */}
        <section className="px-6 pb-4">
          <div className="bg-[#111317] rounded-lg border border-zinc-800/90 overflow-hidden">
            <div className="px-4 py-3 border-b border-zinc-800/80 flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2.5">
                <span className="material-symbols-outlined text-teal-400 text-[18px]">psychology</span>
                <div>
                  <h3 className="text-sm font-semibold text-white tracking-tight">AI Explanation</h3>
                  <p className="font-mono text-[11px] text-zinc-500">
                    Grounded strictly in the rule-engine evidence above — no packet payloads are sent.
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                {explanation ? (
                  <>
                    <span className="font-mono text-[11px] text-zinc-500 hidden sm:inline">
                      {explanation.model ?? "model"} · {explanation.generated_at ? formatClock(explanation.generated_at) : "—"}
                    </span>
                    <button
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-900 border border-zinc-800 text-zinc-200 hover:bg-zinc-800/80 rounded text-xs font-mono transition-colors disabled:opacity-50"
                      type="button"
                      disabled={explaining}
                      onClick={() => runExplanation(true)}
                    >
                      <span className="material-symbols-outlined text-[14px]">autorenew</span>
                      <span>{explaining ? "Regenerating…" : "Regenerate"}</span>
                    </button>
                  </>
                ) : (
                  <button
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-teal-500 text-zinc-950 hover:bg-teal-400 rounded text-xs font-mono font-semibold transition-colors disabled:opacity-50"
                    type="button"
                    disabled={explaining || !analysisId}
                    onClick={() => runExplanation(false)}
                  >
                    <span className="material-symbols-outlined text-[14px]">auto_awesome</span>
                    <span>{explaining ? "Generating…" : "Generate AI explanation"}</span>
                  </button>
                )}
              </div>
            </div>

            <div className="p-4 space-y-3">
              {explaining && !explanation ? (
                <p className="font-mono text-xs text-zinc-500">Querying the model with the deterministic evidence…</p>
              ) : explainError ? (
                <div className="flex items-start gap-2.5 rounded border border-amber-500/25 bg-amber-500/[0.06] px-3.5 py-3">
                  <span className="material-symbols-outlined text-[16px] text-amber-400 mt-0.5">info</span>
                  <div className="flex flex-col gap-0.5">
                    <span className="font-mono text-xs text-amber-200">AI layer unavailable</span>
                    <span className="font-mono text-[11px] text-amber-200/70 break-all">{explainError}</span>
                    <span className="font-mono text-[11px] text-zinc-500">
                      The deterministic findings above are unaffected.
                    </span>
                  </div>
                </div>
              ) : explanation ? (
                <>
                  <p className="text-xs text-zinc-300 leading-relaxed">{explanation.summary}</p>
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                    {explanation.per_finding.map((item, i) => (
                      <div key={`${item.category}-${i}`} className="bg-[#14171c] border border-zinc-800/60 rounded-lg p-3 space-y-1.5">
                        <div className="flex items-center gap-2">
                          <span className={`px-1.5 py-0.5 rounded border font-mono text-[10px] font-bold ${SEV_CHIP[(item.severity || "INFO").toUpperCase()] ?? SEV_CHIP.INFO}`}>
                            {item.severity || "INFO"}
                          </span>
                          <span className="font-mono text-xs font-semibold text-white truncate">{item.category}</span>
                        </div>
                        {item.why ? (
                          <p className="text-[11px] text-zinc-400 leading-relaxed">
                            <span className="text-zinc-500 font-mono uppercase text-[10px]">Why: </span>
                            {item.why}
                          </p>
                        ) : null}
                        {item.remediation ? (
                          <p className="text-[11px] text-zinc-400 leading-relaxed">
                            <span className="text-zinc-500 font-mono uppercase text-[10px]">Fix: </span>
                            {item.remediation}
                          </p>
                        ) : null}
                      </div>
                    ))}
                  </div>
                  <p className="font-mono text-[10px] text-zinc-600 uppercase tracking-wider pt-1">
                    AI-generated analysis · verify against the deterministic findings before acting
                  </p>
                </>
              ) : (
                <p className="font-mono text-xs text-zinc-500">
                  No explanation generated yet for this capture.
                </p>
              )}
            </div>
          </div>
        </section>

        {/* 5. TABLE + INSPECTOR */}
        <section className="px-6 pb-12 grid grid-cols-1 xl:grid-cols-12 gap-6">
          <div className="xl:col-span-7 bg-[#111317] rounded-lg border border-zinc-800/90 flex flex-col overflow-hidden">
            <div className="bg-zinc-900/80 px-4 py-2.5 grid grid-cols-12 gap-3 text-zinc-400 font-mono text-[11px] uppercase tracking-wider select-none border-b border-zinc-800">
              <div className="col-span-3">Severity &amp; ID</div>
              <div className="col-span-4">Finding &amp; Layer</div>
              <div className="col-span-3">Target Scope</div>
              <div className="col-span-2 text-right">Evidence</div>
            </div>

            <div className="divide-y divide-zinc-800/50 flex flex-col text-xs">
              {filtered.map((f, i) => (
                <div
                  key={`${f.category}-${i}`}
                  className={`px-4 py-3 grid grid-cols-12 gap-3 items-center transition-colors cursor-pointer ${selectedRow === i ? "bg-zinc-800/70 border-l-2 border-teal-400" : "hover:bg-zinc-800/30"}`}
                  onClick={() => setSelectedRow(i)}
                >
                  <div className="col-span-3 flex items-center gap-2">
                    <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-bold border ${SEV_CHIP[f.severity] ?? SEV_CHIP.INFO}`}>
                      {f.severity}
                    </span>
                    <span className="font-mono text-zinc-400">F-{String(i + 1).padStart(2, "0")}</span>
                  </div>
                  <div className="col-span-4 flex flex-col min-w-0">
                    <span className="font-semibold text-white truncate">{f.category}</span>
                    <span className="text-zinc-400 text-[11px] truncate">{f.description}</span>
                  </div>
                  <div className="col-span-3 flex flex-col min-w-0 font-mono">
                    <span className="text-zinc-200 truncate">{analysis?.filename ?? "—"}</span>
                    <span className="text-zinc-500 text-[11px] truncate">
                      {analysis?.risk_level ?? "—"} · {analysis?.security_score ?? "—"}/100
                    </span>
                  </div>
                  <div className="col-span-2 flex flex-col items-end gap-0.5">
                    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono text-teal-300 bg-teal-500/10 border border-teal-500/20 font-medium">
                      RULE
                    </span>
                    <span className="font-mono text-[10px] text-zinc-500">Deterministic</span>
                  </div>
                </div>
              ))}
              {filtered.length === 0 && (
                <div className="px-4 py-8 text-center text-zinc-500 font-mono text-xs">
                  {findings.length === 0 ? "No findings were raised for this capture." : "No findings match this filter."}
                </div>
              )}
            </div>
          </div>

          <div className="xl:col-span-5 bg-[#111317] rounded-lg border border-zinc-800/90 p-5 flex flex-col gap-3">
            {selected ? (
              <>
                <div className="flex items-center gap-2">
                  <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-bold border ${SEV_CHIP[selected.severity] ?? SEV_CHIP.INFO}`}>
                    {selected.severity}
                  </span>
                  <span className="text-sm text-white font-semibold">{selected.category}</span>
                </div>
                <p className="text-xs text-zinc-400 leading-relaxed">{selected.description}</p>
                <div className="font-mono text-[11px] text-zinc-500 pt-2 border-t border-zinc-800/60 flex flex-col gap-1">
                  <span>Capture: <span className="text-zinc-300">{analysis?.filename ?? "—"}</span></span>
                  <span>Record: <span className="text-zinc-300">{analysis?.id.slice(0, 8).toUpperCase() ?? "—"}</span></span>
                  <span>Windows: <span className="text-zinc-300">{formatCount(analysis?.config_json?.windows_count ?? null)}</span></span>
                  <span>Evidence: <span className="text-zinc-300">{analysis?.config_json?.evidence_source ?? "unknown"}</span></span>
                </div>
              </>
            ) : (
              <span className="text-xs font-mono text-zinc-500">Select a finding to inspect.</span>
            )}
          </div>
        </section>
      </AppShell>
    </div>
  );
}
