"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useToast } from "@/lib/mock/toast";
import { Footer } from "@/components/layout/Footer";
import { ConstellationCanvas } from "@/components/docs/ConstellationCanvas";
import { StarDrift } from "@/components/docs/StarDrift";
import { DecapsulationPipelineDiagram } from "@/components/docs/DecapsulationPipelineDiagram";
import { HandshakeSequenceDiagram } from "@/components/docs/HandshakeSequenceDiagram";
import { AntiReplaySimulator } from "@/components/docs/AntiReplaySimulator";
import { DiffieHellmanLattice } from "@/components/docs/DiffieHellmanLattice";
import { SystemArchitectureMap } from "@/components/docs/SystemArchitectureMap";
import {
  DocPanel,
  DOC_ACTIVE,
  DOC_IDLE,
} from "@/components/docs/DocChrome";

const CHAPTERS = [
  { id: "prologue", roman: "00", title: "Prologue: What TunnelSight Does Today", category: "System" },
  { id: "chapter-1", roman: "01", title: "The Analysis Pipeline (As Built)", category: "Pipeline" },
  { id: "chapter-2", roman: "02", title: "IKE Versions & the Rule Engine", category: "Protocols" },
  { id: "chapter-3", roman: "03", title: "Scoring: DH, PFS & Anti-Replay", category: "Scoring" },
  { id: "chapter-4", roman: "04", title: "Pages, Routes & API Contracts", category: "Systems" },
  { id: "chapter-5", roman: "05", title: "Findings Into Remediation", category: "Configuration" },
];

const STRONGSWAN_SWANCTL_PATCH = `# /etc/swanctl/conf.d/hardened-ipsec.conf
# Illustrative hardened example (not auto-generated by the current system)
# Conforming to RFC 8247 & NIST SP 800-77 Rev. 1

connections {
  corp-edge-hardened {
    version = 2
    local_addrs = 192.0.2.14
    remote_addrs = 198.51.100.8

    local {
      auth = pubkey
      certs = gateway-cert.pem
      id = fqdn:gw01.corp.internal
    }
    remote {
      auth = pubkey
      id = fqdn:gw04.branch.internal
    }

    # IKE_SA (Phase 1): AEAD-AES-256-GCM + ECP-384 / MODP-3072 + SHA-384 PRF
    proposals = aes256gcm16-prfsha384-ecp384, aes256gcm16-prfsha384-modp3072

    children {
      child-sa-data {
        # CHILD_SA (Phase 2): AEAD-AES-256-GCM with Mandatory PFS (ECP-384)
        esp_proposals = aes256gcm16-ecp384, aes256gcm16-modp3072
        local_ts  = 10.100.0.0/16
        remote_ts = 10.200.0.0/16
        rekey_time = 8h
        dpd_action = restart
        start_action = start
      }
    }
  }
}`;

const STRONGSWAN_IPSEC_CONF_PATCH = `# /etc/ipsec.conf (Legacy strongSwan config)
# Illustrative hardened example (not auto-generated by the current system)
# Hardened against Sweet32, weak DH Group 2, and missing PFS

conn corp-edge-hardened
    keyexchange=ikev2
    left=192.0.2.14
    leftsubnet=10.100.0.0/16
    leftid=@gw01.corp.internal
    leftcert=gateway-cert.pem
    right=198.51.100.8
    rightsubnet=10.200.0.0/16
    rightid=@gw04.branch.internal
    # Phase 1: AEAD + DH Group 20/15 + SHA384
    ike=aes256gcm16-prfsha384-ecp384,aes256gcm16-prfsha384-modp3072!
    # Phase 2: AEAD + PFS Mandatory
    esp=aes256gcm16-ecp384,aes256gcm16-modp3072!
    ikelifetime=24h
    lifetime=8h
    margintime=3m
    dpdaction=restart
    auto=start`;

export default function DocumentationPage() {
  const [activeChapterId, setActiveChapterId] = useState("prologue");
  const [scrollProgress, setScrollProgress] = useState(0);
  const [activePatchTab, setActivePatchTab] = useState<"swanctl" | "ipsec">("swanctl");
  const [copiedPatch, setCopiedPatch] = useState(false);
  // 0 → 1 as the prologue scrolls out: breaks the hero spiral into the gutters
  const disperseRef = useRef(0);
  const toast = useToast();

  useEffect(() => {
    function handleScroll() {
      const total = document.documentElement.scrollHeight - window.innerHeight;
      if (total > 0) {
        setScrollProgress(Math.min(100, Math.max(0, (window.scrollY / total) * 100)));
      }

      // Disperse the hero galaxy laterally as the prologue scrolls out
      const prologue = document.getElementById("prologue");
      if (prologue) {
        const rect = prologue.getBoundingClientRect();
        const raw = Math.min(1, Math.max(0, -rect.top / (rect.height * 0.9)));
        // Smoothstep for a stately, non-linear break
        disperseRef.current = raw * raw * (3 - 2 * raw);
      }

      // Check current chapter in viewport
      for (const ch of CHAPTERS) {
        const el = document.getElementById(ch.id);
        if (el) {
          const rect = el.getBoundingClientRect();
          if (rect.top <= 220 && rect.bottom >= 100) {
            setActiveChapterId(ch.id);
            break;
          }
        }
      }
    }

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToChapter = (id: string) => {
    setActiveChapterId(id);
    const el = document.getElementById(id);
    if (el) {
      const yOffset = -70;
      const y = el.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: "smooth" });
    }
  };

  const copyPatch = (text: string) => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text);
      setCopiedPatch(true);
      toast({ title: "Configuration copied", body: "strongSwan remediation patch copied to clipboard.", kind: "ok" });
      setTimeout(() => setCopiedPatch(false), 2500);
    }
  };

  return (
    <div className="relative min-h-screen bg-[#02040a] text-[#d8d4c7] font-sans antialiased selection:bg-[#d97757]/30 selection:text-[#f7f4ee] flex flex-col justify-between">
      {/* ============ AMBIENT STARDRIFT (page continuity layer) ============ */}
      <StarDrift />

      {/* ============ FIXED GALAXY (formation → gutters, reforms on scroll-up) ============ */}
      <ConstellationCanvas disperseRef={disperseRef} />

      {/* ============ BOTTOM BLUE HUE (cold floor wash) ============ */}
      <div
        className="fixed inset-x-0 bottom-0 h-[42vh] pointer-events-none z-0"
        style={{ background: "linear-gradient(to top, rgba(48, 80, 150, 0.13), transparent)" }}
        aria-hidden="true"
      />

      {/* ============ FILM GRAIN (analog texture, lifts the brights) ============ */}
      <div
        className="fixed inset-0 pointer-events-none z-0 opacity-[0.05]"
        style={{
          backgroundImage:
            "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")",
        }}
        aria-hidden="true"
      />

      {/* ============ VIGNETTE (lit center reads against deep edges) ============ */}
      <div
        className="fixed inset-0 pointer-events-none z-0"
        style={{ background: "radial-gradient(ellipse 90% 80% at 50% 42%, transparent 55%, rgba(0,0,0,0.5) 100%)" }}
        aria-hidden="true"
      />

      {/* ============ READING PROGRESS BAR (WARM ANTHROPIC GRADIENT) ============ */}
      <div className="fixed top-0 inset-x-0 h-[2px] z-50 bg-[#14161a] pointer-events-none">
        <div
          className="h-full bg-gradient-to-r from-[#d97757] via-[#c2b59b] to-[#788c5d] transition-[width] duration-150 ease-out"
          style={{ width: `${scrollProgress}%` }}
        />
      </div>

      {/* ============ QUIET EDITORIAL HEADER ============ */}
      <header className="sticky top-0 z-40 bg-[#02040a]/85 backdrop-blur-xl border-b border-white/[0.06] select-none">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-4">
          {/* Brand lockup */}
          <Link href="/" className="flex items-center gap-2 group shrink-0">
            <span className="font-display-serif text-lg font-bold text-[#f7f4ee] tracking-tight group-hover:text-[#d97757] transition-colors">
              TunnelSight
            </span>
            <span className="hidden sm:inline-block font-mono text-[10px] text-[#8c8a82] uppercase tracking-widest pl-2.5 border-l border-white/[0.1]">
              Systems Dossier
            </span>
          </Link>

          {/* Chapter numerals */}
          <nav className="hidden xl:flex items-center gap-5 text-xs font-mono" aria-label="Chapters">
            {CHAPTERS.map((ch) => (
              <button
                key={ch.id}
                onClick={() => scrollToChapter(ch.id)}
                title={ch.title}
                className={`transition-colors ${
                  activeChapterId === ch.id
                    ? "text-[#d97757]"
                    : "text-[#6b6963] hover:text-[#f7f4ee]"
                }`}
                type="button"
              >
                {ch.roman}
              </button>
            ))}
          </nav>

          {/* Quiet links */}
          <div className="flex items-center gap-5 text-xs font-mono text-[#8c8a82]">
            <button
              onClick={() => scrollToChapter("prologue")}
              className="hidden sm:inline hover:text-[#f7f4ee] transition-colors"
              type="button"
            >
              Index
            </button>
            <button
              onClick={() => scrollToChapter("chapter-5")}
              className="hidden sm:inline hover:text-[#f7f4ee] transition-colors"
              type="button"
            >
              Remediation
            </button>
            <Link href="/overview" className="flex items-center gap-1 text-[#f7f4ee] hover:text-[#d97757] transition-colors">
              <span>Console</span>
              <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
            </Link>
          </div>
        </div>
      </header>

      {/* ============ PROLOGUE / HERO SECTION (ANTHROPIC EDITORIAL PATTERN) ============ */}
      <section
        id="prologue"
        className="relative z-10 pt-24 pb-20 px-4 sm:px-6 max-w-4xl mx-auto text-center border-b border-white/[0.06]"
      >
        <div className="relative space-y-6">
          <div className="inline-flex items-center gap-2 font-mono text-[11px] text-[#b0aea5] uppercase tracking-[0.25em]">
            <span className="w-1.5 h-1.5 rounded-full bg-[#d97757]" />
            <span>September 2026</span>
            <span className="text-zinc-700">·</span>
            <span>Security Engineering &amp; Systems Research</span>
          </div>

          <h1 id="docs-headline" className="font-display-serif text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-[#f7f4ee] leading-[1.1] max-w-3xl mx-auto"
            style={{ textShadow: "0 2px 30px rgba(5,7,13,0.9), 0 1px 8px rgba(5,7,13,0.8)" }}>
            TunnelSight: IPsec Analysis as It Works Today
          </h1>

          <p className="text-base sm:text-lg text-[#d8d4c7] leading-relaxed max-w-2xl mx-auto font-sans"
            style={{ textShadow: "0 1px 20px rgba(5,7,13,0.9)" }}>
            Upload a capture, get a deterministic security score, per-window traffic labels from a RandomForest, anomaly scores from an IsolationForest, and a finding list — all behind session auth, all queryable through the API below. Mock-seeded where packet parsing is not yet wired; every stub says so.
          </p>

          {/* Anthropic Iconic Dotted Leader Table of Contents */}
          <div className="pt-6 pb-2 max-w-xl mx-auto space-y-2.5 font-mono text-xs text-left">
            {CHAPTERS.map((ch) => (
              <button
                key={ch.id}
                onClick={() => scrollToChapter(ch.id)}
                className="group w-full flex items-center justify-between text-[#b0aea5] hover:text-[#f7f4ee] transition-colors py-1 cursor-pointer"
                type="button"
              >
                <span className="text-[#d97757] group-hover:text-[#f7f4ee] font-mono font-semibold shrink-0">
                  [{ch.roman}]
                </span>
                <span className="flex-1 mx-3 border-b border-dotted border-white/20 group-hover:border-white/50 transition-colors" />
                <span className="font-display-serif text-sm text-[#f7f4ee] group-hover:underline decoration-[#d97757] underline-offset-4 truncate">
                  {ch.title}
                </span>
              </button>
            ))}
          </div>

          <div className="pt-3 flex items-center justify-center gap-4 text-xs font-mono text-[#8c8a82]">
            <span>Documented by TunnelSight Core Security Group</span>
            <span>·</span>
            <span>Conforming to RFC 4301 / RFC 7296 / RFC 8247</span>
          </div>

          <blockquote className="border-l-2 border-[#d97757]/60 pl-4 py-1 text-xs sm:text-sm text-[#d8d4c7]/80 italic font-display-serif max-w-xl mx-auto text-left mt-6">
            &ldquo;We stand on the brink of a revolution in cryptography. The development of public-key systems has fundamentally altered the terms under which trust is negotiated over distance.&rdquo;
            <span className="block mt-1 font-mono text-[10px] text-[#d97757] not-italic">
              — Whitfield Diffie &amp; Martin E. Hellman (1976)
            </span>
          </blockquote>
        </div>
      </section>

      {/* ============ CHAPTER I: THE PIPELINE AS BUILT ============ */}
      <section id="chapter-1" className="relative z-10 py-16 px-4 sm:px-6 max-w-5xl mx-auto border-b border-white/[0.06] space-y-8">
        <div className="space-y-3">
          <div className="flex items-center gap-2 font-mono text-xs text-[#d97757] uppercase tracking-wider">
            <span>Chapter I</span>
            <span>·</span>
            <span>Upload → Analyze → Read</span>
          </div>
          <h2 className="font-display-serif text-3xl sm:text-4xl font-bold text-[#f7f4ee] tracking-tight">
            The Analysis Pipeline (As Built)
          </h2>
          <div className="text-sm sm:text-base text-[#b0aea5] leading-relaxed font-sans max-w-3xl space-y-3">
            <p>
              <span className="text-[#f7f4ee] font-mono text-xs">POST /api/analyze</span> accepts a capture
              (.pcap / .pcapng / .cap / .erf, 256 MB cap) and runs it synchronously through{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">AnalyzerService</span>: seeded-mock IPsec
              config + 3–8 seeded 10 s windows of the 18 flow features → RandomForest traffic label
              (+ confidence) and IsolationForest anomaly score per window → deterministic rule-engine
              score. The row lands as <span className="text-[#f7f4ee] font-mono text-xs">completed</span> with
              all typed columns filled; windows go to <span className="text-[#f7f4ee] font-mono text-xs">analysis_windows</span>.
              Same filename always yields the same result (sha256-seeded), so compare and tests are stable.
            </p>
            <p>
              Honest limits: the “parser” is a mock — evidence is seeded, not packet-derived, and every
              response carries that note. No Zeek/tshark, no background worker, no live capture yet.
              The real parser later implements the same window interface without changing any route.
            </p>
          </div>
        </div>

        {/* INTERACTIVE DIAGRAM 1: Decapsulation Pipeline */}
        <DecapsulationPipelineDiagram />
      </section>

      {/* ============ CHAPTER II: IKE + RULE ENGINE ============ */}
      <section id="chapter-2" className="relative z-10 py-16 px-4 sm:px-6 max-w-5xl mx-auto border-b border-white/[0.06] space-y-8">
        <div className="space-y-3">
          <div className="flex items-center gap-2 font-mono text-xs text-[#d8d4c7] uppercase tracking-wider">
            <span>Chapter II</span>
            <span>·</span>
            <span>IKE Versions &amp; Deterministic Assessment</span>
          </div>
          <h2 className="font-display-serif text-3xl sm:text-4xl font-bold text-[#f7f4ee] tracking-tight">
            IKE Versions &amp; the Rule Engine
          </h2>
          <div className="text-sm sm:text-base text-[#b0aea5] leading-relaxed font-sans max-w-3xl space-y-3">
            <p>
              IKEv1 costs −5 (HIGH finding, obsolete); IKEv2 costs nothing. AES-CBC costs −5 (MEDIUM,
              prefer GCM); 3DES / DES / UNKNOWN costs −25 (CRITICAL). Try it live:{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">POST /api/assess/config</span> takes an{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">IPsecConfig</span> and returns{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">{"{total_score, risk_level, findings[]}"}</span> —
              no upload, no DB write. Strong example scores 100/LOW; 3DES + DH2 + no-PFS + IKEv1 + no-replay scores 25/CRITICAL.
            </p>
          </div>
        </div>

        {/* INTERACTIVE DIAGRAM 2: Handshake Sequence */}
        <HandshakeSequenceDiagram />
      </section>

      {/* ============ CHAPTER III: SCORING ============ */}
      <section id="chapter-3" className="relative z-10 py-16 px-4 sm:px-6 max-w-5xl mx-auto border-b border-white/[0.06] space-y-12">
        <div className="space-y-3">
          <div className="flex items-center gap-2 font-mono text-xs text-[#788c5d] uppercase tracking-wider">
            <span>Chapter III</span>
            <span>·</span>
            <span>How the 0–100 Score Is Built</span>
          </div>
          <h2 className="font-display-serif text-3xl sm:text-4xl font-bold text-[#f7f4ee] tracking-tight">
            Scoring: DH, PFS &amp; Anti-Replay
          </h2>
          <div className="text-sm sm:text-base text-[#b0aea5] leading-relaxed font-sans max-w-3xl space-y-3">
            <p>
              Start at 100. DH group missing or below 14: −20 (CRITICAL under 14, HIGH if unknown);
              group 14 exactly: −5 (MEDIUM, minimum bar). PFS disabled: −15 (HIGH). Replay protection
              off: −10 (CRITICAL). Risk bands: ≥90 LOW, ≥70 MEDIUM, ≥50 HIGH, else CRITICAL.
              Parent-row ML aggregation: traffic label = mode of window labels, confidence = mean of the
              winning-label probas, anomaly = worst (min) IsolationForest decision score.
            </p>
          </div>
        </div>

        {/* INTERACTIVE DIAGRAM 3: Diffie-Hellman Lattice */}
        <div className="space-y-4">
          <h3 className="font-display-serif text-xl font-bold text-[#f7f4ee]">
            1. Diffie-Hellman Group Factorization Complexity
          </h3>
          <DiffieHellmanLattice />
        </div>

        {/* INTERACTIVE DIAGRAM 4: Anti-Replay Simulator */}
        <div className="space-y-4">
          <h3 className="font-display-serif text-xl font-bold text-[#f7f4ee]">
            2. RFC 4303 64-Bit Monotonic Anti-Replay Register
          </h3>
          <AntiReplaySimulator />
        </div>
      </section>

      {/* ============ CHAPTER IV: PAGES, ROUTES & CONTRACTS ============ */}
      <section id="chapter-4" className="relative z-10 py-16 px-4 sm:px-6 max-w-5xl mx-auto border-b border-white/[0.06] space-y-8">
        <div className="space-y-3">
          <div className="flex items-center gap-2 font-mono text-xs text-[#d97757] uppercase tracking-wider">
            <span>Chapter IV</span>
            <span>·</span>
            <span>What Exists and How to Call It</span>
          </div>
          <h2 className="font-display-serif text-3xl sm:text-4xl font-bold text-[#f7f4ee] tracking-tight">
            Pages, Routes &amp; API Contracts
          </h2>
          <div className="text-sm sm:text-base text-[#b0aea5] leading-relaxed font-sans max-w-3xl space-y-3">
            <p>
              Auth is a <span className="text-[#f7f4ee] font-mono text-xs">ts_session</span> httpOnly
              cookie (register → login → <span className="text-[#f7f4ee] font-mono text-xs">GET /api/auth/me</span>),
              every fetch with <span className="text-[#f7f4ee] font-mono text-xs">credentials: "include"</span>.
              Upload via multipart to get <span className="text-[#f7f4ee] font-mono text-xs">201 + Location: /api/history/{"{id}"}</span>,
              then read <span className="text-[#f7f4ee] font-mono text-xs">GET /api/history/{"{id}"}/windows|findings|traffic|anomalies</span>,{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">GET /api/compare?alpha=&amp;beta=</span>, and the stub
              set (<span className="text-[#f7f4ee] font-mono text-xs">/api/.../export?format=json|csv, /api/search, /api/datasets/summary, /api/engine/health, POST /api/live/status → {"{supported:false}"}</span>).
              Errors are bare <span className="text-[#f7f4ee] font-mono text-xs">{"{detail}"}</span>: 400 bad file,
              401 unauthenticated, 404 not-owned, 413 oversize, 422 validation. Frontend threads{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">?analysis_id=</span> through
              progress → results → traffic / anomalies / findings / compare, with mock fallback only when{" "}
              <span className="text-[#f7f4ee] font-mono text-xs">NEXT_PUBLIC_USE_MOCK=true</span> and the network fails.
              Not built: live streaming, PDF reports, SMTP reset mail, background workers.
            </p>
          </div>
        </div>

        {/* INTERACTIVE DIAGRAM 5: System Architecture Circuit */}
        <SystemArchitectureMap />
      </section>

      {/* ============ CHAPTER V: FINDINGS INTO ACTION ============ */}
      <section id="chapter-5" className="relative z-10 py-16 px-4 sm:px-6 max-w-5xl mx-auto space-y-8">
        <div className="space-y-3">
          <div className="flex items-center gap-2 font-mono text-xs text-[#d97757] uppercase tracking-wider">
            <span>Chapter V</span>
            <span>·</span>
            <span>From Finding List to Hardened Config</span>
          </div>
          <h2 className="font-display-serif text-3xl sm:text-4xl font-bold text-[#f7f4ee] tracking-tight">
            Findings Into Remediation
          </h2>
          <div className="text-sm sm:text-base text-[#b0aea5] leading-relaxed font-sans max-w-3xl space-y-3">
            <p>
              Each finding carries <span className="text-[#f7f4ee] font-mono text-xs">{"{severity, category, description}"}</span> —
              filterable by severity and text on the findings page, exportable as CSV/JSON. The hardened
              strongSwan snippets below are illustrative references for the most common findings (3DES →
              AES-256-GCM, DH2 → ECP-384, enable PFS); they are not generated per-capture yet.
            </p>
          </div>
        </div>

        {/* Remediation Workbench */}
        <DocPanel className="w-full overflow-hidden font-sans">
          <div className="p-3 border-b border-white/[0.06] flex items-center justify-between flex-wrap gap-2">
            <div className="flex items-center gap-2 font-mono text-xs">
              <button
                onClick={() => setActivePatchTab("swanctl")}
                className={`px-3 py-1 rounded-md transition-all border ${
                  activePatchTab === "swanctl"
                    ? `${DOC_ACTIVE} text-[#f7f4ee] font-semibold`
                    : `${DOC_IDLE} hover:text-[#f7f4ee]`
                }`}
                type="button"
              >
                swanctl.conf (Modern v2)
              </button>
              <button
                onClick={() => setActivePatchTab("ipsec")}
                className={`px-3 py-1 rounded-md transition-all border ${
                  activePatchTab === "ipsec"
                    ? `${DOC_ACTIVE} text-[#f7f4ee] font-semibold`
                    : `${DOC_IDLE} hover:text-[#f7f4ee]`
                }`}
                type="button"
              >
                ipsec.conf (Legacy strongSwan)
              </button>
            </div>

            <button
              onClick={() =>
                copyPatch(
                  activePatchTab === "swanctl"
                    ? STRONGSWAN_SWANCTL_PATCH
                    : STRONGSWAN_IPSEC_CONF_PATCH
                )
              }
              className="flex items-center gap-1.5 px-3 py-1 rounded-md bg-transparent border border-white/15 text-[#d8d4c7] hover:text-[#f7f4ee] hover:border-white/25 text-xs font-mono transition-all"
              type="button"
            >
              <span className="material-symbols-outlined text-[15px]">
                {copiedPatch ? "check" : "content_copy"}
              </span>
              <span>{copiedPatch ? "COPIED TO CLIPBOARD" : "COPY PATCH"}</span>
            </button>
          </div>

          <pre className="p-6 font-mono text-xs text-[#d8d4c7] leading-relaxed overflow-x-auto selection:bg-[#d97757]/30 selection:text-white">
            <code>
              {activePatchTab === "swanctl"
                ? STRONGSWAN_SWANCTL_PATCH
                : STRONGSWAN_IPSEC_CONF_PATCH}
            </code>
          </pre>
        </DocPanel>
      </section>

      {/* ============ FOOTER SECTION WITH AURORA ============ */}
      <Footer tone="dark" accent="ember" />
    </div>
  );
}
